services:
  app:
    container_name: my-nest-minikube-study
    build: .
    env_file: .env
    ports:
      - '${PORT}:${PORT}'
    networks:
      - app-network
    depends_on:
      - db
    restart: always

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:

networks:
  app-network:
