apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-mariadb-minikube-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs-mariadb-minikube-example
  template:
    metadata:
      labels:
        app: nestjs-mariadb-minikube-example
    spec:
      containers:
        - name: nestjs-mariadb-minikube-example
          image: nestjs-mariadb-minikube-example:latest # Dockerfile을 빌드한 이미지 이름으로 변경
          imagePullPolicy: Never # 도커 이미지를 외부에서 가져오지 않도록 설정
          ports:
            - containerPort: 3000 # 실제 포트 번호로 변경
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
