apiVersion: v1
kind: Service
metadata:
  name: nestjs-mariadb-minikube-example-service
spec:
  selector:
    app: nestjs-mariadb-minikube-example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000 # 실제 포트 번호로 변경
  type: LoadBalancer
